angular.module('acount',['ngRoute','canhe.service'])
  .config(['$routeProvider',function($routeProvider){
    $routeProvider
      .when('/login',{
        templateUrl:'templates/login.html',
        controller:'loginCtrl'
      })
      .when('/register',{
        templateUrl:'templates/reg.html',
        controller:'registerCtrl'
      })
      .otherwise({
        redirectTo:'/login'
      })
  }])
  .controller('userCtrl',['$scope',function($scope){

  }])
  .controller('loginCtrl',['$rootScope','$scope','$interval','dataService',function($rootScope,$scope,$interval,dataService){
    $rootScope.title='登录';
    $scope.proving='获取验证码';
    $scope.user={
      name:'',
      password:'',
      yanzheng:''
    };
    $scope.submitLogin=function(valid){
      //console.log('start login');
      console.log(valid);
      if(valid){
        console.log($scope.user);
        dataService.login($scope.user);
        //console.log($scope.user.name);
        //console.log($scope.user.password);
        //console.log($scope.user.yanzheng);
      }
    }

    //修改登录方式
    $scope.loginMethod=true;
    $scope.loginType=function(){
      if($scope.loginMethod){
        $scope.loginMethod=false;
      }else{
        $scope.loginMethod=true;
      }
      console.log($scope.loginMethod);
    }

    //获取验证码时间限制，限制一分钟后再获取验证码
    $scope.getProveBtn=false;
    var intervalId;
    $scope.getProving=function(){
      if($scope.getProveBtn){
        return;
      }
      $scope.getProveBtn=true;
      var time=120;
      $scope.proving=time+'秒后获取';
      intervalId=$interval(function(){
        if(time>1){
          time--;
          $scope.proving=time+'秒后获取';
        }else{
          $interval.cancel(intervalId);
          $scope.getProveBtn=false;
          $scope.proving='获取验证码';
        }
      },1000);
      $scope.$on('$destroy',function(){
        if(intervalId){
          $interval.cancel(intervalId);
        }
      })
    }
    $scope.$on('$destory',function(){
      if(intervalId){
        $interval.cancel(intervalId);
      }
    })
  }])
  .controller('registerCtrl',['$rootScope','$scope','$interval',function($rootScope,$scope,$interval){
    $rootScope.title='注册';
    $scope.proving='获取验证码';
    $scope.submitReg=function(valid){

    }

    //获取验证码限制，限制2分钟后才能再次获取验证码
    $scope.getProveBtn=false;
    var intervalId
    $scope.getProving=function(){
      if($scope.getProveBtn){
        return;
      }
      $scope.getProveBtn=true;
      var time=120;
      $scope.proving=time+'秒后获取';
      intervalId=$interval(function(){
        if(time>1){
          time--;
          $scope.proving=time+'秒后获取';
        }else{
          $interval.cancel(intervalId);
          $scope.getProveBtn=false;
          $scope.proving='获取验证码';
        }
      },1000);
      //清除获取验证码的倒计时函数
      $scope.$on('$destroy',function(){
        if(intervalId){
          $interval.cancel(intervalId);
        }
      })
    }
  }])